version: "3.9"

services:
  postgres:
    image: postgres
    container_name: entry_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: entry
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data
    networks:
      - entry_network
    restart: always

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: entry_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - entry_network
    restart: always

networks:
  entry_network:
    driver: bridge