# Generated by Django 3.2 on 2022-07-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.entry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='lap_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
