# Generated by Django 3.2 on 2022-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20220724_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='max_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lap',
            name='total_elapsed_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='cadence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
