# Generated by Django 3.2 on 2022-07-24 19:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0003_auto_20220724_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-created',), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='lap',
            options={'ordering': ('-created',), 'verbose_name': 'Lap', 'verbose_name_plural': 'Laps'},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ('-created',), 'verbose_name': 'Point', 'verbose_name_plural': 'Points'},
        ),
        migrations.AddField(
            model_name='lap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='point',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.FileField(upload_to='entry/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'fit', 'gpx', 'kml', 'tcx'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='avg_heart_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Avg heart rate'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='max_heart_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Max heart rate'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='max_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Max speed'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='number',
            field=models.IntegerField(blank=True, help_text='NOTE: It is not unique, just useful in multiple laps', null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='total_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Total distance'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='total_elapsed_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Total elapsed time'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='point',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='cadence',
            field=models.FloatField(blank=True, null=True, verbose_name='cadence'),
        ),
        migrations.AlterField(
            model_name='point',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.entry', verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='point',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Heart rate'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lap_number',
            field=models.IntegerField(blank=True, help_text='NOTE: It is not unique, just useful in multiple laps', null=True, verbose_name='Lap number'),
        ),
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='point',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='point',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
